### Get - Get Theme By Id
< {%
    import {wait} from "./scripts/Wait"

    wait(2)
%}

GET {{host}}{{sep-themes-port}}/experience-themes/api/v1/themes?id={{addedThemeId}}
bmw-canary: {{bmw-canary}}
bmw-gcid: {{bmw-gcid}}
bmw-home-market: PT

> ./scripts/Get-ThemeById.js
