apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-application-properties
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |-
{{ .Files.Get .Values.cmPath | indent 4 }}
