{{ if eq .Chart.Name  "sep-app-cargos-canary" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    team: {{ .Values.team }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers -s "503 429" "Retry-After: 3600";
    nginx.ingress.kubernetes.io/proxy-body-size: 60m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '16'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/canary: 'true'
    nginx.ingress.kubernetes.io/canary-by-header: {{ .Values.canary.header }}
    nginx.ingress.kubernetes.io/canary-by-header-pattern: {{ .Values.canary.regex | quote }}
    kubernetes.io/ingress.class: private-nginx
spec:
  tls:
    - hosts:
      {{- range $host := .Values.canary.hosts }}
        - {{ $host }}
      {{- end }}
      secretName: {{ .Release.Namespace }}-tls
  rules:
  {{- range $host := .Values.canary.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /experience-cargos(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Chart.Name }}
                port:
                  name: http
  {{- end }}
{{ end }}