apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Values.releaseVersion | quote }}
    team: {{ .Values.team }}
    stage: {{ .Release.Namespace }}
type: Opaque
data:
  java_truststore_password: {{ .Values.truststorePassword | b64enc }}
  memorydb_password: {{ .Values.cachePass | b64enc }}
  {{- if and (eq .Values.environment "e2e") (eq .Values.region "eu-central-1") }}
  contrastAPIUsername: {{ .Values.contrastAPIUsername | b64enc | quote }}
  contrastAPIKey: {{ .Values.contrastAPIKey | b64enc | quote }}
  contrastAPIServiceKey: {{ .Values.contrastAPIServiceKey | b64enc | quote }}
  {{- end }}
stringData:
  memorydb_encryption_key: {{ .Values.cacheEncryptionKey }}
  authorization_token: Bearer {{ .Values.authorizationToken }}
