### GET - Get Experiences

< {%
    client.global.set("requestId", "getThemesById2");
    client.global.set("ignoreKeys", `["downloadDate"]`);
%}

GET {{host}}{{sep-themes-port}}/experience-themes/api/v1/themes
bmw-gcid: {{bmw-gcid}}
bmw-home-market: IT
bmw-canary: true

> ../scripts/assertEqualResponse.js
