### POST - Add User

POST {{host}}{{app-capela-port}}/nc-cargas/api/v1/user
bmw-canary: {{bmw-canary}}
Authorization: {{authorization}}
Content-Type: application/json

{
    "mail":"lou@ren.co",
    "name":"Lourenço",
    "phoneNumber":"987 0980 34",
    "address":"Listal",
    "id": "ddrtetre"
}

> ./scripts/Post-AddTheme.js