name: Cleanup Workflows by Status
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

  workflow_dispatch:  # Allows manual triggering
    inputs:
      status:
        type: choice
        description: Workflow status to delete
        default: failure
        options:
          - failure
          - cancelled


jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Job details
        shell: bash
        run: |
          echo "Inputs: ${{ toJSON(inputs) }}"

      - name: Delete all ${{ inputs.status }} workflows
        shell: bash
        run: |
          echo "Deleting all ${{ inputs.status }} workflows for ${{ github.repository }}"
          gh run list --repo ${{ github.repository }} --status ${{ inputs.status }} --json databaseId --jq '.[].databaseId' | xargs -I {} gh run delete {}
