name: Cleanup Workflows by Status
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

  workflow_dispatch:  # Allows manual triggering
    inputs:
      status:
        type: choice
        description: Workflow status to delete
        default: failure
        options:
          - failure
          - cancelled
          - success

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete all ${{ inputs.status }} workflows
        run: |
          gh run list --repo ${{ github.repository }} --status ${{ inputs.status }} --json databaseId --jq '.[].databaseId' | xargs -I {} gh run delete {}
