name: Deploy With Canary
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        default: test
        options:
          - test
          - int
      hub:
        type: choice
        description: Select the Hub
        default: emea
        options:
          - emea
      run-integration-tests:
        type: boolean
        description: Run integration tests?
        default: false
      dry-run:
        type: boolean
        description: Dry run test?
        default: false
      canary-upgrade-mode:
        type: choice
        description: Canary upgrade mode
        default: remove-after-tests
        options:
          - remove-after-tests
          - keep-after-tests

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.hub }}-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  deploy-canary:
    name: Deploy Canary
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      hub: ${{ inputs.hub }}
      release-version: ${{ github.event.release.tag_name }}
      run-integration-tests: ${{ inputs.run-integration-tests }}
      dry-run: ${{ inputs.dry-run }}
      canary-deploy: true
      canary-percentage: 0
      canary-upgrade-mode: ${{ inputs.canary-upgrade-mode }}
    secrets:
      TECHNICAL_USER_TOKEN: ${{ secrets.TECHNICAL_USER_TOKEN }}
      TECHNICAL_USER_USERNAME: ${{ secrets.TECHNICAL_USER_USERNAME }}
      TECHNICAL_USER_PASSWORD: ${{ secrets.TECHNICAL_USER_PASSWORD }}
      TECHNICAL_USER_ARTIFACTORY_TOKEN: ${{ secrets.TECHNICAL_USER_ARTIFACTORY_TOKEN }}

  deploy-stable:
    name: Deploy Stable
    uses: ./.github/workflows/deploy.yml
    needs: deploy-canary
    with:
      environment: ${{ inputs.environment }}
      hub: ${{ inputs.hub }}
      release-version: ${{ github.event.release.tag_name }}
      run-integration-tests: ${{ inputs.run-integration-tests }}
      dry-run: ${{ inputs.dry-run }}
      canary-deploy: false
    secrets:
      TECHNICAL_USER_TOKEN: ${{ secrets.TECHNICAL_USER_TOKEN }}
      TECHNICAL_USER_USERNAME: ${{ secrets.TECHNICAL_USER_USERNAME }}
      TECHNICAL_USER_PASSWORD: ${{ secrets.TECHNICAL_USER_PASSWORD }}
      TECHNICAL_USER_ARTIFACTORY_TOKEN: ${{ secrets.TECHNICAL_USER_ARTIFACTORY_TOKEN }}