name: Build and Publish Quarkus Image with Jib

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Test secret access
        run: echo "The secret is accessed but not shown for security reasons"
        env:
          MY_SECRET: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Log in to Docker Hub
        run: |
          echo "User is: ${{ secrets.DOCKER_HUB_PASSWORD }}" 
          echo "pass is: ${{ secrets.DOCKER_HUB_USERNAME }}"
          docker login -u ${{ secrets.DOCKER_HUB_PASSWORD }} -p ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build and push Docker image with Jib
        run: ./mvnw compile jib:build \
          -Djib.to.image=${{ secrets.DOCKER_HUB_USERNAME }}/quarkus-app:${{ github.sha }} \
          -Djib.to.auth.username=${{ secrets.DOCKER_HUB_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.DOCKER_HUB_PASSWORD }}
