name: Build and Publish Quarkus Image with Jib

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Test secret access
        run: echo "The secret is accessed but not shown for security reasons"
        env:
          MY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          MY_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Log into Docker Hub
        run: docker login -u lolmeida -p L0#nasval


      - name: Build and push Docker image with Jib
        run: ./mvnw compile jib:build \
          -Djib.to.image=${{ secrets.DOCKER_HUB_USERNAME }}/quarkus-app:${{ github.sha }} \
          -Djib.to.auth.username=lolmeida \
          -Djib.to.auth.password=L0#nasval
