name: Setup Docker Hub & Publish Quarkus Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: peah-pipelines-templates/actions/publish-dockerhub-image@main

