name: Hotfix Release
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-analysis:
    name: Code Analysis
    uses: peah-pipelines-templates/.github/workflows/code-analysis.yml@main
    with:
      overwrite-settings: true
      settings-server-id: artifactory
    secrets:
      settings-server-username: ${{ secrets.TECHNICAL_USER_USERNAME }}
      settings-server-password: ${{ secrets.TECHNICAL_USER_ARTIFACTORY_TOKEN }}

  deploy-int:
    name: Deploy to Int
    uses: ./.github/workflows/deploy.yml
    needs: code-analysis
    with:
      hub: emea
      environment: int
      run-integration-tests: true
      type-of-release: hotfix
    secrets:
      TECHNICAL_USER_USERNAME: ${{ secrets.TECHNICAL_USER_USERNAME }}
      TECHNICAL_USER_PASSWORD: ${{ secrets.TECHNICAL_USER_PASSWORD }}
      TECHNICAL_USER_TOKEN: ${{ secrets.TECHNICAL_USER_TOKEN }}
      TECHNICAL_USER_ARTIFACTORY_TOKEN: ${{ secrets.TECHNICAL_USER_ARTIFACTORY_TOKEN }}